### PR TITLE
32 enhance roll event handling

### LINKED ISSUE #32: Enhance `Roll` event handling
- [x] Fallback: If event filter setup fails, start polling `getLogs` for the `Roll` event.
- [x] Timeout: If no event is received in time, switch to polling.
- [ ] Filter upgrade: Listen for `Roll` events by player address (not betId), filter betId client-side, and start listening before calling `wager`.

### PR DESCRIPTION
**Pull request by Maweill**
closes #32

### CODE REVIEW

File: examples/mini-app/src/hooks/types.ts [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+  currency: string
+  rolled: COINTOSS_FACE
+}
+
+export interface WatchTarget {
+  betId: bigint
+  contractAddress: Hex
+  gameType: CASINO_GAME_TYPE
+  eventAbi: Abi
+  eventName: string
```
Comment (utgarda) [inline examples/mini-app/src/hooks/types.ts:16]: Not in this PR:

can we put these 4 values to a mostly static, initialized once for a single game, context?

File: examples/mini-app/src/hooks/usePlaceBet.ts [hunk 2]
```diff
@@ -255,18 +217,23 @@ async function _extractBetIdFromReceipt(
...
+  logger.debug("_extractBetIdFromReceipt: Receipt received.")
 
   const placeBetEventDefinition = placeBetAbi.find(
     (item) => item.type === "event" && item.name === "PlaceBet",
   )
 
   if (!placeBetEventDefinition) {
-    console.warn("PlaceBet event definition not found in ABI.")
+    logger.warn(
+      "_extractBetIdFromReceipt: PlaceBet event definition not found in ABI.",
```
Comment (utgarda) [inline examples/mini-app/src/hooks/usePlaceBet.ts:235]: if "public client undefined" condition results in an error, should this be an error too?

Can this result in people making bets and seeing nothing, just a warning in console?

Can placeBetEventDefinition be non-nullable and defined as early as possible?

**Review by utgarda — APPROVED** [review]
The code looks good to me, 
works too!

File: examples/mini-app/src/hooks/types.ts (hunk 1 above)
Comment (Maweill) [reply examples/mini-app/src/hooks/types.ts:16]: The `useBetResultWatcher` hook is already generic enough (with some tweaks) to handle any game without overly complicating the code. Therefore, we can use this type when developing another game.
